name: Deploy React App to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Deploy to Ubuntu Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP1 }}
          username: ${{ secrets.SERVER_USER1 }}
          key: ${{ secrets.SSH_PRIVATE_KEY1 }}
          port: 22
          source: "build/*"
          target: "/var/www/my-react-app"
          strip_components: 1